CREATE TABLE `bills` (
  `id` int(11) NOT NULL,
  `comp_id` varchar(255) DEFAULT NULL,
  `bill_number` varchar(255) DEFAULT NULL,
  `bill_type` varchar(255) DEFAULT NULL,
  `customer_id` varchar(255) DEFAULT NULL,
  `bill_date` date DEFAULT NULL,
  `due_date` varchar(255) DEFAULT NULL,
  `total_amount` decimal(10,2) DEFAULT NULL,
  `cparty` varchar(255) DEFAULT NULL,
  `gtotal` varchar(100) NOT NULL DEFAULT '0',
  `sgsttotal` varchar(100) NOT NULL DEFAULT '0',
  `cgsttotal` varchar(100) NOT NULL DEFAULT '0',
  `payment_status` varchar(255) DEFAULT 'Unpaid',
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp()
);



CREATE TABLE `items_details` (
  `id` int(11) NOT NULL,
  `bill_id` int(11) NOT NULL,
  `po_date` varchar(255) DEFAULT NULL,
  `po_id` varchar(11) DEFAULT NULL,
  `delivery_date` varchar(255) DEFAULT NULL,
  `delivery_time` varchar(255) DEFAULT NULL,
  `site_name` varchar(255) DEFAULT NULL,
  `supplier_name` varchar(255) DEFAULT NULL,
  `item_code` varchar(11) DEFAULT NULL,
  `hsn_code` varchar(11) DEFAULT NULL,
  `item_name` varchar(255) DEFAULT NULL,
  `qty` varchar(11) DEFAULT NULL,
  `uom` varchar(255) DEFAULT NULL,
  `rate` varchar(102) DEFAULT NULL,
  `gst_rate` varchar(255) DEFAULT NULL,
  `gst_amount` varchar(102) DEFAULT NULL,
  `cess_amount` varchar(102) DEFAULT NULL,
  `delivery_charges` varchar(102) DEFAULT NULL,
  `gst_delivery_charge` varchar(102) DEFAULT NULL,
  `others_amount` varchar(102) DEFAULT NULL,
  `gst_on_other_amount` varchar(255) DEFAULT NULL,
  `category_name` varchar(255) DEFAULT NULL,
  `item_type` varchar(255) DEFAULT NULL,
  `item_ops` varchar(255) DEFAULT NULL,
  `po_status` varchar(255) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `username` varchar(255) DEFAULT NULL,
  `timestamp` datetime DEFAULT current_timestamp(),
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp()
)
